Here is everything you are going to need to run this notebook

nltk.download('all')

pip install pyenchant 
pip install autocorrect

Here we get all the info from the lexicons and the training tweets 
then we fix the training tweets so as to be used for data analysis
Insted of the word tokenizer we use the TweetTokenizer.

In [ ]:

from read_files import read_all,read_train_tsv,read_dict
lexs = read_all()
tsv =read_train_tsv()
from fix_tweets import wd_rem
fixed_tweets,hash_tags,name_tags=wd_rem(tsv)    #fix the tweets so that they can be used for 
                                                #the wordcloud and data analysis

#from nltk.tokenize import word_tokenize
from nltk.tokenize import TweetTokenizer
tknzr = TweetTokenizer()

import enchant
d = enchant.Dict("en_US")
words=read_dict()


Here is where the analysis happens

In [ ]:

wd_text=""
for tweet_info in fixed_tweets:
    tweet_info[0]=tknzr.tokenize(tweet_info[0].lower())
    wd_text+=" ".join(tweet_info[0])
    for word in tweet_info[0]:
        if not d.check(word):
            if word not in words:
                print(word)

#wd_text=""
#for tweet in hash_tags:
 #   wd_text+=" "+tweet

In [ ]:
'''
import numpy as np
import matplotlib.pyplot as plt
import random
from PIL import Image
from os import path ,getcwd
from wordcloud import WordCloud
from colour_wc import random_color_func
from nltk.corpus import stopwords

d = path.dirname(__file__) if "__file__" in locals() else getcwd()
mask = np.array(Image.open(path.join(d, "twitter_mask.png")))

nltk_stopwords = set(stopwords.words('english'))
nltk_WC = WordCloud(background_color="white",max_words=500, mask=mask, stopwords=nltk_stopwords, margin=10,
               random_state=1).generate(wd_text)

plt.figure(figsize=[7,7])
plt.imshow(nltk_WC.recolor(color_func=random_color_func, random_state=3),
           interpolation="bilinear")
plt.axis("off")
plt.show()
nltk_WC.to_file("twitter_nlyk_WC.png")
'''


Bag of words
Here we will again tokenize the tweets but in a different way.


In [5]:
import nltk
nltk.download('all')


[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package brown to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     /home/

[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     /home/rafael/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading

True

In [6]:
from nltk.corpus import stopwords
nltk_stopwords = set(stopwords.words('english'))

from nltk.tokenize import TweetTokenizer
tknzr = TweetTokenizer(strip_handles=True, reduce_len=True)

from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
from autocorrect import spell

from read_files import read_all,read_train_tsv,read_dict
#lexs = read_all()
tsv =read_train_tsv()
from fix_tweets import wd_rem

import enchant
d = enchant.Dict("en_US")
words=read_dict()

fixed_tweets,hash_tags,name_tags=wd_rem(tsv)    #fix the tweets so that they can be used for 

#    tweet_info[0]=
tweets=[]
import csv
"""
with open('twitter.tsv', 'wt') as out_file:
    tsv_writer = csv.writer(out_file, delimiter='\t')
    for tweet in fixed_tweets:
        tw=tweet[0]
        tw=tknzr.tokenize(tw)
        for word in tw:
            if word in nltk_stopwords:
                tw.remove(word)
            else:
                if (not d.check(word)) and (word not in words):                        
                    word=stemmer.stem(spell(word))
                else:
                    word=stemmer.stem(word)
    
        tw = " ".join(tw)
        tsv_writer.writerow([tw])
        tweets.append(tw)
print("as")"""

#add vocabulary
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words=nltk_stopwords ,max_features=500)

print( vectorizer.fit_transform(tweets).todense() )
print( vectorizer.vocabulary_)

as
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'house': 208, 'hit': 202, 'going': 169, 'sat': 372, 'still': 407, 'shit': 387, 'watch': 472, 'deal': 100, 'saturday': 373, 'fan': 131, 'hate': 193, 'wait': 465, 'february': 134, 'says': 376, 'keep': 233, 'talking': 418, 'like': 250, 'may': 281, 'end': 116, 'mon': 297, 'obama': 320, 'via': 460, 'vote': 463, 'whole': 484, 'movie': 301, 'harry': 192, 'christmas': 76, 'th': 422, 'team': 419, 'make': 272, 'week': 478, 'tomorrow': 440, 'want': 469, 'go': 165, 'college': 83, 'happy': 189, 'day': 97, 'june': 229, 'im': 210, 'hope': 204, 'get': 159, 'apple': 17, 'san': 370, 'monday': 298, 'watched': 473, 'remember': 360, 'sun': 410, 'one': 327, 'best': 43, 'excited': 127, 'today': 437, 'lol': 256, 'open': 328, 'set': 386, 'play': 338, 'next': 312, 'wednesday': 477, 'come': 84, 'great': 179, 'tell': 420, 'november': 319, 'release': 359, 'date': 95, 'true': 447, 'big': 47, '

In [52]:
import pandas as pd
dataset_train = pd.read_csv('twitter11111111111.tsv', encoding='utf8',delimiter='\t');
dataset_test = pd.read_csv("../twitter_data/test2017.tsv", encoding='utf8',delimiter='\t');
dataset_tr = pd.read_csv("../twitter_data/train2017.tsv", encoding='utf8',delimiter='\t');

corpus=[]
for i in range(dataset_train.shape[0]):
    tweet = dataset_train.iloc[i, 0]
    corpus.append(tweet)
    
test_tweets=[]   
for i in range(dataset_test.shape[0]):
    tweet = dataset_test.iloc[i, 3]
    test_tweets.append(tweet) 

#csv_output = []
#file_path="../twitter_data/train2017.tsv"
#with open(file_path, 'r',encoding='utf8',errors="ignore") as f_input:
 #   csv_input = csv.reader(f_input, delimiter='\t', skipinitialspace=True)
  #  for cols in csv_input:
  #      csv_output.append(cols[2])    
#print(csv_output)

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words=nltk_stopwords ,max_features=1000)

#print( vectorizer.fit_transform(corpus).todense() )
#print( vectorizer.vocabulary_)   
X = vectorizer.fit_transform(corpus).toarray()
y = dataset_tr.iloc[:, 2]
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X, y)
X_test= vectorizer.fit_transform(test_tweets).toarray()

y_pred = classifier.predict(X_test)

In [59]:
dataset_gl = pd.read_csv("../twitter_data/SemEval2017_task4_subtaskA_test_english_gold.txt", encoding='utf8',delimiter='\t');

y_test=dataset_gl.iloc[:, 1]
#print(y_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

    negative       0.30      0.32      0.31      3972
     neutral       0.50      0.34      0.41      5936
    positive       0.18      0.31      0.23      2375

    accuracy                           0.33     12283
   macro avg       0.33      0.32      0.32     12283
weighted avg       0.38      0.33      0.34     12283

